CREATE TABLE AD_CONTENT
(
    AD_CONTENT_ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CLICKTRACKERS varchar(255),
    LINK_URL varchar(1000),
    TITLE varchar(255) NOT NULL
);
CREATE UNIQUE INDEX UNIQUE_TITLE_INDEX_5 ON AD_CONTENT (TITLE);
CREATE TABLE AD_CONTENT_ASSET
(
    ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DATA_LABEL varchar(255),
    DATA_VALUE varchar(1000),
    IMAGE_HEIGHT integer,
    IMAGE_URL varchar(1000),
    IMAGE_WIDTH integer,
    CLICKTRACKERS varchar(255),
    LINK_URL varchar(1000),
    DATA_NULLOR_DATA_VALUE_NULL boolean,
    IMG_NULLOR_IMG_URL_NULL boolean,
    LINK_NULLOR_LINK_URL_NULL boolean,
    TITLE_TEXT varchar(255),
    AD_CONTENT_ID integer,
    CONSTRAINT FK5PSROQF8GTGN0YQ3FSI6COAME FOREIGN KEY (AD_CONTENT_ID) REFERENCES AD_CONTENT (AD_CONTENT_ID)
);
CREATE TABLE AD_CONTENT_IMPRESSION_URL
(
    AD_CONTENT_ID integer NOT NULL,
    IMPRESSION_URL varchar(1000) NOT NULL,
    CONSTRAINT CONSTRAINT_9 PRIMARY KEY (AD_CONTENT_ID, IMPRESSION_URL),
    CONSTRAINT FK_IMPRESSION_URL FOREIGN KEY (AD_CONTENT_ID) REFERENCES AD_CONTENT (AD_CONTENT_ID)
);
CREATE TABLE AD_CONTENT_VIEW_URL
(
    AD_CONTENT_ID integer NOT NULL,
    VIEW_URL varchar(1000) NOT NULL,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (AD_CONTENT_ID, VIEW_URL),
    CONSTRAINT FK_VIEW_URL FOREIGN KEY (AD_CONTENT_ID) REFERENCES AD_CONTENT (AD_CONTENT_ID)
)